### ISSUE TITLE
XAxis' object has no attribute '_gridOnMajor

### ISSUE THREAD

**Issue by dmiller7115** [mpld3/mpld3#479]
Hello, matplotlib recently merged a change that removed provide variables from Axis: matplotlib/matplotlib#18769. 

I hit this bug when converting matplotlib to html.
* matplotlib>=3.3.3
* mpld3==0.5.1

Reproduce by:
```
import mpld3
import matplotlib.pyplot as plt
fig = plt.figure(1)
ax = plt.plot([1,2,3])
mpld3.fig_to_html(fig)
```
Results in
```
~/venv/lib/python3.7/site-packages/mpld3/mplexporter/utils.py in get_grid_style(axis)
    261 def get_grid_style(axis):
    262     gridlines = axis.get_gridlines()
--> 263     if axis._gridOnMajor and len(gridlines) > 0:
    264         color = export_color(gridlines[0].get_color())
    265         alpha = gridlines[0].get_alpha()

AttributeError: 'XAxis' object has no attribute '_gridOnMajor'
```

**Comment by carlinmack** [comment]
There is a fix suggested here https://github.com/plotly/plotly.py/issues/2913

**Comment by keitayabu** [comment]
I have to quite ! No PC has been 3years . If your pea rents die or become Red country what’s wold you do .
Lost your son . You can spend normal life. Or make new san with someone else?  You understand ?
Do not have PC because no measly to live . Like a North .....who look like a telephone .

iPhoneから送信

**Comment by cliffckerr** [comment]
Thank you @dmiller7115 and @carlinmack -- we'll try to get this fixed in the next few days. Main thing to check is that the fix doesn't break anything for previous version of Matplotlib.

**Comment by vladh** [comment]
Hey everyone, thank you for the report and for the information.

I've fixed this in https://github.com/mpld3/mplexporter/compare/2f766e439b9d91ab4d4682245a2360bc1e5c2bb5...be8e3da62c81fea15a0107f3ae96ba16fc2cc9f

I've confirmed that the fix suggested by @carlinmack works for matplotlib versions 3.3.3, 3.2.1 and 2.2.5.

The fix will be available as soon as I push out the new version, which will be ASAP.

Let me know if you encounter any problems!

**Comment by carlinmack** [comment]
thanks for testing! I didn't think about backwards compatibility, but glad to hear it works okay!

**Comment by vladh** [comment]
Fixed in release 0.5.2 in https://github.com/mpld3/mpld3/commit/4617a12d7d0cafd636e66bc65a709e2aab22c0e6 !

**Comment by tobiz** [comment]
As of 20220527 I still get this problem ('XAxis' object has no attribute '_gridOnMajor') with the example of dmiller7115 running kubuntu 21.10, python 3.9.7, matplotlib 3.5.2, plotly 5.8.0 - all python modules standard install.  However the only difference is the line in issue is line 247, ie "if axis._gridOnMajor and len(gridlines) > 0:"

**Comment by vladh** [comment]
@tobiz Line 247 of what file? Doing an `ack "_gridOnMajor"` gives me nothing, hmm…

**Comment by tobiz** [comment]
Sorry! 
This where it's installed in the VM;  similar to the file ref in dmiller7115's install.
/usr/lib/python3/dist-packages/plotly/matplotlylib/mplexporter/utils.py

**Comment by vladh** [comment]
@tobiz It sounds like your problem is not with mpld3 but with "matplotlylib" — I'm not sure what that is, but it sounds like you have the wrong repo! :P

**Comment by bryevdv** [comment]
> wrong repo

Certainly but in the spirit of helpfulness it is probably worth mentioning the obvious conclusion, which is that the other project has vendored an old / out of date version of [mpld3/mplexporter](https://github.com/mpld3/mplexporter)
